In [1]:
import pandas as pd

In [4]:
df=pd.DataFrame({
    "Department":["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Employee":["Rakesh", "Sikha", "Anil", "Priya", "John", "Ram"],
    "Salary":[5000,6000,7000,8000,5500,9000],
    "Age":[25,30,28,35,32,40]
})

In [5]:
df

  Department Employee  Salary  Age
0         IT   Rakesh    5000   25
1         HR    Sikha    6000   30
2         IT     Anil    7000   28
3    Finance    Priya    8000   35
4         HR     John    5500   32
5    Finance      Ram    9000   40

In [6]:
df.head(5)

  Department Employee  Salary  Age
0         IT   Rakesh    5000   25
1         HR    Sikha    6000   30
2         IT     Anil    7000   28
3    Finance    Priya    8000   35
4         HR     John    5500   32

In [7]:
df.tail(6)

  Department Employee  Salary  Age
0         IT   Rakesh    5000   25
1         HR    Sikha    6000   30
2         IT     Anil    7000   28
3    Finance    Priya    8000   35
4         HR     John    5500   32
5    Finance      Ram    9000   40

In [10]:
df.describe()

            Salary        Age
count     6.000000   6.000000
mean   6750.000000  31.666667
std    1541.103501   5.316641
min    5000.000000  25.000000
25%    5625.000000  28.500000
50%    6500.000000  31.000000
75%    7750.000000  34.250000
max    9000.000000  40.000000

In [11]:
df[1:3]

  Department Employee  Salary  Age
1         HR    Sikha    6000   30
2         IT     Anil    7000   28

In [12]:
df[3:5]

  Department Employee  Salary  Age
3    Finance    Priya    8000   35
4         HR     John    5500   32

In [14]:
result=df.groupby('Department')['Salary'].sum()
result

Department
Finance    17000
HR         11500
IT         12000
Name: Salary, dtype: int64

In [15]:
avg=df.groupby('Department')['Salary'].mean()

In [16]:
avg

Department
Finance    8500.0
HR         5750.0
IT         6000.0
Name: Salary, dtype: float64

In [18]:
count=df.groupby('Department')['Employee'].count()
count

Department
Finance    2
HR         2
IT         2
Name: Employee, dtype: int64

In [19]:
maxSal=df.groupby('Department')['Salary'].max()
maxSal

Department
Finance    9000
HR         6000
IT         7000
Name: Salary, dtype: int64

In [31]:
total_sal_IT=df[df['Department']=='IT']['Salary'].sum()

In [36]:
print(f'total IT salary is',total_sal_IT)

total IT salary is 12000

In [37]:
total_sal_HR=df[df['Department']=='HR']['Salary'].sum()
print(f'total HR salary is',total_sal_HR)

total HR salary is 11500

In [38]:
total_sal_fin=df[df['Department']=='Finance']['Salary'].sum()

In [39]:
print(f'total Finance salary is',total_sal_fin)

total Finance salary is 17000

In [43]:
result=df.groupby("Department").agg({
    "Salary":["sum","mean","max"],
    "Age":["min","max"]})
result

           Salary               Age
              sum    mean   max min max
Department
Finance     17000  8500.0  9000  35  40
HR          11500  5750.0  6000  30  32
IT          12000  6000.0  7000  25  28

In [49]:
df2=pd.DataFrame({
    "Department":["IT","IT", "HR","HR","Finance","Finance"],
    "Gender":["M","F","F","M","F","M"],
    "Salary":[5000,7000,6000,5500,8000,9000]
        })

In [50]:
df2

  Department Gender  Salary
0         IT      M    5000
1         IT      F    7000
2         HR      F    6000
3         HR      M    5500
4    Finance      F    8000
5    Finance      M    9000

In [53]:
res=df2.groupby(['Department','Gender'])['Salary'].sum()

In [54]:
res

Department  Gender
Finance     F         8000
            M         9000
HR          F         6000
            M         5500
IT          F         7000
            M         5000
Name: Salary, dtype: int64

In [57]:
res.to_csv('groupCol.csv')

In [58]:
df=pd.read_csv('groupCol.csv')
df

  Department Gender  Salary
0    Finance      F    8000
1    Finance      M    9000
2         HR      F    6000
3         HR      M    5500
4         IT      F    7000
5         IT      M    5000

In [59]:
for index, row in df.iterrows():
    print(f"Department:{row['Department']}")
    print(f"Gender:{row['Gender']}")
    print(f"Salary:{row['Salary']}")
    print("-"*30)

Department:Finance
Gender:F
Salary:8000
------------------------------
Department:Finance
Gender:M
Salary:9000
------------------------------
Department:HR
Gender:F
Salary:6000
------------------------------
Department:HR
Gender:M
Salary:5500
------------------------------
Department:IT
Gender:F
Salary:7000
------------------------------
Department:IT
Gender:M
Salary:5000
------------------------------

In [80]:
result=df.groupby("Department").agg({
    "Salary":["mean"],
    "Gender":["count"]}).reset_index()
result

  Department  Salary Gender
                mean  count
0    Finance  8500.0      2
1         HR  5750.0      2
2         IT  6000.0      2