In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url="https://books.toscrape.com/"
response=requests.get(url)

In [6]:
s=BeautifulSoup(response.text,"html.parser")

In [9]:
books=[]
for b in s.find_all("article", class_="product_pod"):
    title= b.h3.a['title']
    price=b.find("p",class_="price_color").text
    rating=b.find("p")["class"][1]
    books.append(
        {
            'Title':title,
            'Price':price,
            'rating':rating
        }
    )
books

[{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'rating': 'Three'},
 {'Title': 'Tipping the Velvet', 'Price': 'Â£53.74', 'rating': 'One'},
 {'Title': 'Soumission', 'Price': 'Â£50.10', 'rating': 'One'},
 {'Title': 'Sharp Objects', 'Price': 'Â£47.82', 'rating': 'Four'},
 {'Title': 'Sapiens: A Brief History of Humankind',
  'Price': 'Â£54.23',
  'rating': 'Five'},
 {'Title': 'The Requiem Red', 'Price': 'Â£22.65', 'rating': 'One'},
 {'Title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Price': 'Â£33.34',
  'rating': 'Four'},
 {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Price': 'Â£17.93',
  'rating': 'Three'},
 {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Price': 'Â£22.60',
  'rating': 'Four'},
 {'Title': 'The Black Maria', 'Price': 'Â£52.15', 'rating': 'One'},
 {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'Price': 'Â£13.99',
  'rating': 'Two'},
 {'Title': "Shakespeare's Sonnets", 'Price': 'Â£20.66', 'rating': 'Four'},
 {'Title': 'Set Me Free', 'Price': 'Â£17.46', 'rating': 'Five'},
 {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Price': 'Â£52.29',
  'rating': 'Five'},
 {'Title': 'Rip it Up and Start Again', 'Price': 'Â£35.02', 'rating': 'Five'},
 {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Price': 'Â£57.25',
  'rating': 'Three'},
 {'Title': 'Olio', 'Price': 'Â£23.88', 'rating': 'One'},
 {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Price': 'Â£37.59',
  'rating': 'One'},
 {'Title': 'Libertarianism for Beginners',
  'Price': 'Â£51.33',
  'rating': 'Two'},
 {'Title': "It's Only the Himalayas", 'Price': 'Â£45.17', 'rating': 'Two'}]

In [22]:
df=pd.DataFrame(books)
df

                                                Title    Price rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [23]:
pd.DataFrame(df['Title'])

                                                Title
0                                A Light in the Attic
1                                  Tipping the Velvet
2                                          Soumission
3                                       Sharp Objects
4               Sapiens: A Brief History of Humankind
5                                     The Requiem Red
6   The Dirty Little Secrets of Getting Your Dream...
7   The Coming Woman: A Novel Based on the Life of...
8   The Boys in the Boat: Nine Americans and Their...
9                                     The Black Maria
10     Starving Hearts (Triangular Trade Trilogy, #1)
11                              Shakespeare's Sonnets
12                                        Set Me Free
13  Scott Pilgrim's Precious Little Life (Scott Pi...
14                          Rip it Up and Start Again
15  Our Band Could Be Your Life: Scenes from the A...
16                                               Olio
17  Mesaerion: The Best Science Fiction Stories 18...
18                       Libertarianism for Beginners
19                            It's Only the Himalayas

In [24]:
title=df['Title']
price=df['Price']
rating=df['rating']

In [25]:
price

0     Â£51.77
1     Â£53.74
2     Â£50.10
3     Â£47.82
4     Â£54.23
5     Â£22.65
6     Â£33.34
7     Â£17.93
8     Â£22.60
9     Â£52.15
10    Â£13.99
11    Â£20.66
12    Â£17.46
13    Â£52.29
14    Â£35.02
15    Â£57.25
16    Â£23.88
17    Â£37.59
18    Â£51.33
19    Â£45.17
Name: Price, dtype: str

In [54]:
price=price.replace(r'[^0-9.]','',regex=True)
price

0     51.77
1     53.74
2     50.10
3     47.82
4     54.23
5     22.65
6     33.34
7     17.93
8     22.60
9     52.15
10    13.99
11    20.66
12    17.46
13    52.29
14    35.02
15    57.25
16    23.88
17    37.59
18    51.33
19    45.17
Name: Price, dtype: float64

In [55]:
price=price.astype(float)
df.Price.dtype

dtype('float64')

In [56]:
total_price=price.sum()
total_price

np.float64(760.97)

In [59]:
df.to_csv('book-price-rating.csv')

In [60]:
df.count()

Title     20
Price     20
rating    20
dtype: int64